/**
 * Reads and writes myst config through the `yaml` Document API, which keeps the author's keys,
 * order and comments; never a text patch [R3].
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseDocument, type Document } from 'yaml';
import { BRAND_ASSET_KEYS, type OwnOverride } from './compose.js';
import { EDITION_ID } from './schema.js';
import * as msg from './messages.js';
import { UserError } from './messages.js';

/**
 * The derived config oak builds from [R71]: the author's `myst.yml` plus the `extends:` chain
 * and compose's additions. It sits at the paper root because myst resolves `toc`,
 * `bibliography`, plugins and brand assets relative to the config. It is not deleted after a
 * build, since myst exits the process on success [R67.3]; the paper template gitignores it.
 */
export const DERIVED_CONFIG_FILE = 'myst.oak.yml';

const DERIVED_BANNER =
  ' GENERATED by `oak build`: do not edit, do not commit.\n' +
  ' Your config is `myst.yml`; this is it composed with the engine/edition/brand chain.\n' +
  ' Regenerated on every build; safe to delete.';

export function readDoc(path: string): Document {
  return parseDocument(readFileSync(path, 'utf8'));
}

export function writeDoc(path: string, doc: Document): void {
  writeFileSync(path, doc.toString());
}

/** Writes the derived config with a banner saying it is generated from `myst.yml`. */
export function writeDerivedDoc(path: string, doc: Document): void {
  doc.commentBefore = DERIVED_BANNER;
  writeFileSync(path, doc.toString());
}

/** Reads the version and edition from the author's myst.yml before any merge, as the engine
 *  action does, so it works before the journal is resolved [design §6a]. A missing value is the
 *  author's to fix, so it throws a {@link UserError} naming the file. */
export function readEngineCoordinateRaw(
  doc: Document,
  mystPath = 'myst.yml',
): { version: string; edition: string } {
  const version = doc.getIn(['project', 'options', 'oaktree-sapling', 'version']);
  const edition = doc.getIn(['project', 'options', 'oaktree-sapling', 'edition']);
  if (typeof version !== 'string' || !version) {
    throw new UserError(msg.build.missingEngineCoordinate('version', mystPath));
  }
  if (typeof edition !== 'string' || !edition) {
    throw new UserError(msg.build.missingEngineCoordinate('edition', mystPath));
  }
  // Checked here too: this value picks a file in `extendsChainFor` before anything validates the
  // merged config [R141].
  if (!EDITION_ID.safeParse(edition).success) {
    throw new UserError(msg.build.badEdition(edition, mystPath));
  }
  return { version, edition };
}

/** Reads the asset fields from `<instanceRoot>/brand/brand.yml` itself, not the merged config,
 *  so only the brand's own assets are resolved against it and a paper's relative path is left
 *  alone [R62]. Returns `site.options` (HTML) and `project.options.logo` (the PDF watermark);
 *  empty when absent. */
export function readBrandAssetOptions(instanceRoot: string): {
  site: Record<string, string>;
  project: Record<string, string>;
} {
  const brandPath = join(instanceRoot, 'brand', 'brand.yml');
  const empty = { site: {}, project: {} };
  if (!existsSync(brandPath)) return empty;
  const doc = parseDocument(readFileSync(brandPath, 'utf8'));
  const lift = (namespace: 'site' | 'project', keys: readonly string[]) => {
    const out: Record<string, string> = {};
    for (const key of keys) {
      const value = doc.getIn([namespace, 'options', key]);
      if (typeof value === 'string' && value) out[key] = value;
    }
    return out;
  };
  return {
    site: lift('site', BRAND_ASSET_KEYS.site),
    project: lift('project', BRAND_ASSET_KEYS.project),
  };
}

/** Reads `typst_template:` from `<instanceRoot>/journal.yml`: the journal's template, between
 *  the author's and oak's [R76]. It lives in journal.yml, which myst never reads, because
 *  brand.yml is a myst config layer and myst warns about keys it does not know. */
export function readTenantTypstTemplate(instanceRoot: string): string | undefined {
  const journalPath = join(instanceRoot, 'journal.yml');
  if (!existsSync(journalPath)) return undefined;
  const value = parseDocument(readFileSync(journalPath, 'utf8')).get('typst_template');
  return typeof value === 'string' && value ? value : undefined;
}

/** Reads the author's own typst `template:` from `<paperRoot>/myst.yml`. The composed config
 *  cannot say who set it, since compose always stamps one [R79] [R82], so the override check
 *  [R76] reads it here. Undefined when absent or unreadable; that is another check's finding. */
export function readAuthorTypstTemplate(paperRoot: string): string | undefined {
  const authorPath = join(paperRoot, 'myst.yml');
  if (!existsSync(authorPath)) return undefined;
  let config: unknown;
  try {
    config = parseDocument(readFileSync(authorPath, 'utf8')).toJS();
  } catch {
    return undefined;
  }
  const exports = (config as { project?: { exports?: unknown } } | null)?.project?.exports;
  if (!Array.isArray(exports)) return undefined;
  const typst = exports.find(
    (e): e is Record<string, unknown> =>
      !!e && typeof e === 'object' && (e['format'] === 'typst' || e['id'] === 'typst-pdf'),
  );
  const template = typst?.['template'];
  return typeof template === 'string' && template ? template : undefined;
}

/** Pass 1: replaces any `extends:` with oak's chain. A migrated paper may still carry old URL
 *  pins. */
export function setExtends(doc: Document, chain: string[]): void {
  if (chain.length === 0) doc.delete('extends');
  else doc.set('extends', chain);
}

/** Pass 2: merges compose's additions: `project.exports`, `site.template`, and single asset
 *  keys under `site.options` and `project.options` [R62]. Keys are set one by one so the
 *  author's other options, and the `oaktree-sapling` key, survive. */
export function applyOwnOverride(doc: Document, override: OwnOverride): void {
  if (override.project?.exports) {
    doc.setIn(['project', 'exports'], override.project.exports);
  }
  if (override.project?.options) {
    for (const [key, value] of Object.entries(override.project.options)) {
      doc.setIn(['project', 'options', key], value);
    }
  }
  if (override.site?.template) {
    doc.setIn(['site', 'template'], override.site.template);
  }
  if (override.site?.options) {
    for (const [key, value] of Object.entries(override.site.options)) {
      doc.setIn(['site', 'options', key], value);
    }
  }
}
